Логика доски и минимальные функции
wezzen/deeplay-intership-2023 pull request #10
Opened 2023-07-31 10:00 UTC by Simon170522

Добавил метод добавления камня в Board.

2023-07-31 10:08 UTC, wezzen requested changes

2023-07-31 10:08 UTC, wezzen commented on modules/server/src/main/java/io/deeplay/inership/server/Board.java
> +    public boolean setStone(int xPosition, int yPosition, Color stoneColor) {
Тесты

2023-07-31 10:08 UTC, wezzen commented on modules/server/src/main/java/io/deeplay/inership/server/Board.java
> +    private boolean isEmptyCell(int xPosition, int yPosition) {
Тесты

2023-07-31 10:08 UTC, wezzen commented on modules/server/src/main/java/io/deeplay/inership/server/Board.java
> +    private boolean isEmptyCell(int xPosition, int yPosition) {
Пара x и y похоже на экземпляр класса Cell

2023-07-31 10:08 UTC, wezzen commented on modules/server/src/main/java/io/deeplay/inership/server/Board.java
> +    private Stone[][] field;
Точно Stone?

2023-07-31 10:08 UTC, wezzen commented on modules/server/src/main/java/io/deeplay/inership/server/GameRecord.java
> +    private final List<Board> gameHistory;
Опять-таки похоже на отдельную сущность

2023-07-31 10:08 UTC, wezzen commented on modules/server/src/main/java/io/deeplay/inership/server/Player.java
> +public class Player {
Лишнее. Не имеет смысла такой класс в таком виде

2023-07-31 10:12 UTC, MiracleBell commented on modules/server/src/main/java/io/deeplay/inership/server/Board.java
> +    private Stone[][] field;
> Точно Stone?

Таки решили, что лучше будет Stone, чем Color, т.к. не придется искать на ij-й позиции принадлежность камня к конкретной группе

2023-07-31 10:17 UTC, Angedon commented on modules/server/src/main/java/io/deeplay/inership/server/Board.java
> +    private Stone[][] field;
Ну по идее да, Stone, в каждой ячейке стоит Stone, у которого три возможных состояния: EMPTY(еще он тут не существует фактически), BLACK, WHITE.

2023-07-31 10:23 UTC, MiracleBell requested changes

2023-07-31 10:23 UTC, MiracleBell commented on modules/server/src/main/java/io/deeplay/inership/server/GameRecord.java
У этой сущности нет полей

2023-07-31 16:55 UTC, Simon170522 commented on modules/server/src/main/java/io/deeplay/inership/server/GameRecord.java
> +    private final List<Board> gameHistory;
Убрал. Другие дополнят

2023-08-01 05:41 UTC, MiracleBell reviewed
Эх, нас ждет огромное количество конфликтов при слиянии веток)

2023-08-01 05:41 UTC, MiracleBell commented on modules/server/src/main/java/io/deeplay/inership/server/Board.java
> +        return answer;
Не вижу смысла таскать флаг answer
```
if (isEmptyCell(cell)){
field[cell.getX()][cell.getY()].setColor(stoneColor)
return true;
}
return false;```

2023-08-01 05:41 UTC, MiracleBell commented on modules/server/src/main/java/io/deeplay/inership/server/Board.java
> +    }
Для того, чтобы проще было прочитать, лучше разделить длинное условие на отдельные строки
```
return (cell.getX() <= (SIZE - 1) && 
cell.getX() >= 0) && 
(cell.getY() <= (SIZE - 1) && 
cell.getY() >= 0);
```

2023-08-01 05:41 UTC, MiracleBell commented on modules/server/src/main/java/io/deeplay/inership/server/Cell.java
> +}
В моем PR Дима уже писал об этом. Т.к. Cell хранит в себе координаты и не будет изменяться, то лучше использовать record-класс (появился с 16 версией java) [Документация по record](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Record.html)

2023-08-01 05:49 UTC, Simon170522 commented on modules/server/src/main/java/io/deeplay/inership/server/Board.java
> +        return answer;
Разницы особой нет, кроме того что выделяется дополнительный байт в памяти. Кто-то считает что лучше написать много выходов для каждой ситауции, кто-то говорит что выход должен быть один. Это дело вкуса

2023-08-01 07:49 UTC, MiracleBell submitted a review, later dismissed

2023-08-01 08:34 UTC, MiracleBell approved these changes

2023-08-03 06:15 UTC, closed without merging