Inship 14
wezzen/deeplay-intership-2023 pull request #17
Opened 2023-08-03 16:01 UTC by Angedon

Сделал метод формирования групп, а также метод удаления групп, если они задохнулись. Оба метода работают по системе после каждого хода можно их вызвать.

2023-08-03 19:43 UTC, MiracleBell requested changes

2023-08-03 19:43 UTC, MiracleBell commented on modules/game-service/src/main/java/io/deeplay/intership/service/Validation.java
> +        }
Получится убрать повторение кода? В GroupControl точно такой код (строки 21-32)

2023-08-03 19:43 UTC, MiracleBell commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +    }
При удалении не проверяется количество дыханий у группы. И почему алгоритм позволяет удаляет только одну группу? Теоретически одним ходом можно удалить от 1 до 4 вражеских групп.

2023-08-03 19:43 UTC, MiracleBell commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +            }).get();
Возможно так было бы короче без потери читаемости
![изображение](https://github.com/wezzen/deeplay-intership-2023/assets/72202450/3fa99d6f-25ba-42c1-bd1e-9894aa945017)

2023-08-03 19:43 UTC, MiracleBell commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +            maxStone.getGroup().addFreeCells(getNearStones(stone, Color.EMPTY));
Тут мы разве не прибавляем все свободны клетки - 1. Т.к. камень, который мы добавляем будет занимать свободное поле у группы, к которой мы его добавляем

2023-08-03 19:43 UTC, MiracleBell commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +                if(friendStone != maxStone){
здесь лучше сравнивать не камни а группы, иначе может получиться повторное чтение группы и ее перезапись. Например у нас есть несколько friendStone, принадлежащих одной группе. При этом maxStone будет выбран один, и проверку friendStone != maxStone они пройдут, а принадлежат они к одной группе.

2023-08-03 19:43 UTC, MiracleBell commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +                        }
Камень меняет ссылку на новую группу и все. Но при этом он остается в старой группе и сама группа не удаляется В объекте Board из сета групп

2023-08-04 03:32 UTC, Angedon commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +    }
Исправил опечатку, там проверка дыхания, конечно же, должна быть вместо количества камней. Алгоритм все группы проверяет, так как он проверяет каждую группу каждого вражеского камня по соседству (если у этой группы < 2 дыханий).

2023-08-04 03:33 UTC, Angedon commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +            maxStone.getGroup().addFreeCells(getNearStones(stone, Color.EMPTY));
Да, забыл эту строку, добавил.

2023-08-04 03:33 UTC, Angedon commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +                if(friendStone != maxStone){
Справедливо.

2023-08-04 03:37 UTC, Angedon commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +                        }
На 90-й строке удаляется группа из сета групп. maxStone.getGroup().addStones(friendGroup.getStones()); в этой строке все камни добавляются разом в большую группу.

2023-08-04 03:39 UTC, Angedon commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +    private Board board;
Но мы же меняем состояния ячеек доски, в том числе при удалении stone.setColor(Color.EMPTY).

2023-08-04 03:42 UTC, Angedon commented on modules/game-service/src/main/java/io/deeplay/intership/service/Validation.java
> +                }
Суть в том, что если рядом есть хотя бы 1 группа с 1-м даме, то он может встать рядом, он ее уничтожит.

2023-08-04 03:44 UTC, Angedon commented on modules/game-service/src/main/java/io/deeplay/intership/service/Validation.java
> +                }
Если же у всех групп вражеских больше одного даме, значит это суицид, так как вокруг кроме врагов никого нет, находимся в условии пустоты множества друзей по соседству.

2023-08-04 03:46 UTC, Angedon commented on modules/game-service/src/main/java/io/deeplay/intership/service/Validation.java
> +        }
Это поле приватное.

2023-08-04 03:46 UTC, Angedon commented on modules/game-service/src/main/java/io/deeplay/intership/service/Validation.java
> +        }
Исправил.

2023-08-04 03:51 UTC, MiracleBell commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +    private Board board;
> Но мы же меняем состояния ячеек доски, в том числе при удалении stone.setColor(Color.EMPTY).

Так final будет объект Board. Это не значит, что нам нельзя менять его состояние. Грубо говоря, final для объекта - когда мы не можем переприсвоить ссылку на этот объект.

2023-08-04 03:59 UTC, MiracleBell commented on modules/game-service/src/main/java/io/deeplay/intership/service/Validation.java
> +        }
> Это поле приватное.

я не про DEFAULT_BOARD_SIZE, можно через board.getField() получить игровое поле, а у него есть конкретный размер

2023-08-04 04:02 UTC, Angedon commented on modules/game-service/src/main/java/io/deeplay/intership/service/GroupControl.java
> +    Set<Stone> getNearStones(Stone stone, Color color){
Я нахожу Set<Stone> emptyStones, Set<Stone> enemyStones, Set<Stone> friendStones, два из этих сета имеют другой цвет, суть этого метода именно в том чтобы найти рядом камни определенного цвета.

2023-08-04 05:45 UTC, Simon170522 approved these changes

2023-08-04 10:33 UTC, closed without merging