Inship 167
wezzen/deeplay-intership-2023 pull request #41
Opened 2023-08-14 15:53 UTC by Angedon

Добавил DTO для запросов и ответов при взаимодействии между клиентом и сервером.

2023-08-14 17:51 UTC, MiracleBell requested changes
В дополнение. Не исключено, что десериализация запросов и сериализация ответов будут в одном месте. Следовательно может случиться конфликт имен CreateGameDto(request) и CreateGameDto(response). Как вариант, можно указывать в названии dto: CreateGameDtoRequest и CreateGameDtoResponse.

2023-08-14 17:51 UTC, MiracleBell commented on modules/dto/build.gradle.kts
> +    implementation(project(mapOf("path" to ":model")))
нет необходимости в `mapOf(...)`
используй:
```kothlin
implementation(project(":model"))
```

2023-08-14 17:51 UTC, MiracleBell commented on modules/dto/src/main/java/io/deeplay/intership/dto/request/CreateGameDTO.java
> +public record CreateGameDTO(RequestType requestType, Boolean withBot, String color, Integer size, String token) {
Зачем использовать обертки для примитивов, если можно использовать сами примитивы: boolean вместо Boolean, int вместо Integer?

2023-08-14 17:51 UTC, MiracleBell commented on modules/dto/src/main/java/io/deeplay/intership/dto/request/LogInDTO.java
> +public record LogInDTO(RequestType requestType, String login, String passwordHash) {
Настолько часто это слово пишут слитно, что оно закрепилось, как неделимое. Когда-то мне сделали замечание на счет этого, поэтому запомнил, как оно должно быть. В java классы называют существительными, методы - глаголами. `Login` - существительное, `log in` - глагол. => `LoginDto`, все по правилам CamelCase
[Login или log in](https://habr.com/ru/articles/313774/)

2023-08-14 17:51 UTC, MiracleBell commented on modules/dto/src/main/java/io/deeplay/intership/dto/request/LogOutDTO.java
> +public record LogOutDTO(RequestType requestType, String token) {
Смотри комментарий про login

2023-08-14 17:51 UTC, MiracleBell commented on modules/dto/src/main/java/io/deeplay/intership/dto/request/PassDTO.java
> +public record PassDTO(RequestType requestType, String token) {
Возможно, что стоит указывать game-id? Вроде бы это было в протоколе или что-то путаю?

2023-08-14 17:51 UTC, MiracleBell commented on modules/dto/src/main/java/io/deeplay/intership/dto/request/SurrenderDTO.java
> +public record SurrenderDTO(RequestType requestType, String token) {
См. комментарий про game-id

2023-08-14 17:51 UTC, MiracleBell commented on modules/dto/src/main/java/io/deeplay/intership/dto/request/TurnDTO.java
> +public record TurnDTO(RequestType requestType, String color, Integer row, Integer column, String token) {
См. комментарий про game-id

2023-08-14 17:51 UTC, MiracleBell commented on modules/dto/src/main/java/io/deeplay/intership/dto/response/DuringGameDTO.java
> +public record DuringGameDTO(String message, String status, Stone[][] gameField) {
По названию не совсем понятно, для чего dto. Может быть лучше использовать *MoveDto*?

2023-08-14 17:51 UTC, MiracleBell commented on modules/dto/src/main/java/io/deeplay/intership/dto/response/FinishDTO.java
> +public record FinishDTO(String message, String status, Integer blackScore, Integer whiteScore) {
Почему бы не конкретизировать, что именно должно закончиться. К примеру, FinishGameDto?

2023-08-14 17:51 UTC, MiracleBell commented on modules/dto/src/main/java/io/deeplay/intership/dto/response/RegistrationLogoutJoinDTO.java
> +public record RegistrationLogoutJoinDTO(String message, String status) {
Лучше придумать, что-то универсальное или общее. А это dto будет подходить для 5-10 ситуаций, то не перечислять же их все в названии класса. Как вариант InfoDto, или SuccessDto.

2023-08-14 17:51 UTC, MiracleBell commented on modules/dto/src/test/java/io/deeplay/internship/dto/DTOTest.java
> +    public void checkRegistrationRequest(){
Тесты нужны для всех dto. Очень заметно просело покрытие тестами.

2023-08-14 18:45 UTC, wezzen commented on modules/dto/src/main/java/io/deeplay/intership/dto/RequestType.java
> +    FINISH_GAME
А это что за запрос такой будет?

2023-08-15 04:05 UTC, Angedon commented on modules/dto/src/main/java/io/deeplay/intership/dto/RequestType.java
> +    FINISH_GAME
Получить финальный счет, понять, кто выиграл, завершить игру.

2023-08-15 05:45 UTC, Angedon commented on modules/dto/src/main/java/io/deeplay/intership/dto/request/PassDTO.java
> +public record PassDTO(RequestType requestType, String token) {
Мы же вроде как сошлись на том, что по UID мы точно понимаем в какой игре сейчас игрок находится, что вроде как не нужен тут game-id, если я правильно помню.

2023-08-15 06:40 UTC, MiracleBell approved these changes

2023-08-15 07:00 UTC, closed without merging