Inship 174
wezzen/deeplay-intership-2023 pull request #66
Opened 2023-08-25 15:35 UTC by Simon170522

2023-08-25 17:04 UTC, MiracleBell requested changes

2023-08-25 17:04 UTC, MiracleBell commented on modules/user-interface/terminal-ui/src/main/java/io/deeplay/intership/ui/terminal/Display.java
> +        System.out.print("Введите логин и пароль через пробел " + "\n");
Тут одно из двух: либо нажмите 2 и введите в отдельной инструкции логин и пароль, либо ввести логин и пароль без всяких "нажмите 2".

2023-08-25 17:13 UTC, Simon170522 commented on modules/client/src/main/java/io/deeplay/intership/client/Client.java
> +            FileInputStream fis = new FileInputStream("src/main/resources/config.properties");
зачем?

2023-08-26 17:41 UTC, Simon170522 commented on modules/user-interface/terminal-ui/src/main/java/io/deeplay/intership/ui/terminal/Display.java
> +        System.out.print("Введите логин и пароль через пробел " + "\n");
да, тут надо подумать. Потому что ситуация у нас меняется, а вот под обстоятельства не получается подстроить вывод

2023-08-26 18:06 UTC, wezzen commented on modules/decision-maker/src/main/java/io/deeplay/intership/decision/maker/DecisionMakerTerminal.java
> +        if ((int) (Math.random() * 2 + 1.0) == 1) {
Math.random() > 0.5

2023-08-26 18:07 UTC, wezzen commented on modules/decision-maker/src/main/java/io/deeplay/intership/decision/maker/DecisionMakerTerminal.java
> +public class DecisionMakerTerminal implements DecisionMaker {
по содержанию класса я бы назвал его TerminalUIController

2023-08-27 06:06 UTC, MiracleBell approved these changes

2023-08-27 06:06 UTC, merged