Inship 267
wezzen/deeplay-intership-2023 pull request #87
Opened 2023-09-04 10:42 UTC by MiracleBell

2023-09-04 11:36 UTC, Angedon approved these changes

2023-09-04 11:52 UTC, wezzen requested changes

2023-09-04 11:52 UTC, wezzen commented on modules/server/src/main/java/io/deeplay/intership/server/GameController.java
> +    public String createGame(CreateGameDtoRequest dtoRequest) {
не соглашусь. Думаю, правильней если принимаешь dto то и возвращаешь dto, а снаружи пусть занимаются сериализаций/десериализацией

2023-09-04 11:52 UTC, wezzen commented on modules/server/src/main/java/io/deeplay/intership/server/GameController.java
> +        this(new UserService(), new GameService(), new JSONConverter(), clientId);
nit: не хорошая практика, я так понимаю внутри статическая хранилка пользователей и игр. Сейчас исправлять не будем (долго) но в целом лучше передавать объекты и стараться минимизировать использование static

2023-09-04 11:52 UTC, wezzen commented on modules/game/src/main/java/io/deeplay/intership/game/Game.java
> +            throw new GameException(GameCode.FINISHED);
имхо нехватка информации. Вылетит эксепшн FINISHED и не совсем понятен контекст. Лучше дополнительно указать, что "игрок пытается сделать пасс, когда игра уже завершена". Можно в GameException добавить message

2023-09-04 11:52 UTC, wezzen commented on modules/server/src/test/java/io/deeplay/intership/server/GameControllerTest.java
> +public class GameControllerTest {
пустой класс не нужно коммитить

2023-09-04 11:52 UTC, wezzen commented on modules/service/src/main/java/io/deeplay/intership/service/GameService.java
> +    public <T extends BaseDtoResponse> T pass(final PassDtoRequest dtoRequest) throws ServerException {
Зачем generic?

2023-09-05 15:35 UTC, MiracleBell commented on modules/dao/src/main/java/io/deeplay/intership/dao/file/UserDaoImpl.java
> +        try (BufferedReader reader = new BufferedReader(new FileReader(CREDENTIALS_FILE_NAME))) {
Эта альтернатива нравится больше, чем создавать экземпляр коллекции в классе Server и таскать его через ClientHandler и контроллеры (тем самым раздувая их конструкторы). + в таком случае придется переделывать тесты

2023-09-05 15:37 UTC, MiracleBell commented on modules/dao/src/main/java/io/deeplay/intership/dao/file/GameDaoImpl.java
> +    private static final String ACTIVE_PLAYERS = "active_sessions.txt";
> нужно ли это? типа для восстановления состоянии игр при падении сервера?

Восстановления в планах не было, скорее это позволяет отслеживать игровые сессии, опять же, чтобы не таскать лишние коллекции из Server.

2023-09-06 03:50 UTC, Angedon submitted a review, later dismissed

2023-09-06 11:29 UTC, wezzen commented on modules/dao/src/main/java/io/deeplay/intership/dao/file/GameDaoImpl.java
> +    private static final String ACTIVE_PLAYERS = "active_sessions.txt";
выглядит так себе, я уже не говорю о производительности) каждый раз лезть в файл, чтобы проверить есть ли у нас какая-то игровая сессия. + как ты будешь решать проблемы параллельных многопоточных сессий? Используй Map просто. Если не хочется протаскивать все сервисы из сервера - создай класс-агрегатор сервисов и пробрасывай только его, а там внутри уже все экземпляры нужных сервисов

2023-09-06 11:34 UTC, wezzen commented on modules/dao/src/main/java/io/deeplay/intership/dao/file/UserDaoImpl.java
> +        try (BufferedReader reader = new BufferedReader(new FileReader(CREDENTIALS_FILE_NAME))) {
тебе между сессиями сервера нужна хранить пользователей, которые уже зарегистрирвались, окей, храни в файле, никто не требует БД. но в рантайме работай с коллелкциями. Если тебе нужно что-то записать новое в файл - записывай, но сортировку, поиск делай в коллекции

2023-09-08 10:45 UTC, Angedon approved these changes

2023-09-09 06:20 UTC, Angedon approved these changes

2023-09-09 08:18 UTC, wezzen requested changes

2023-09-09 08:18 UTC, wezzen commented on modules/aggregator/src/main/java/io/deeplay/intership/util/aggregator/DataCollectionsAggregator.java
> +        try (BufferedReader reader = new BufferedReader(new FileReader(CREDENTIALS_FILE_NAME))) {
тут этого не должно быть. у тебя есть UserDaoImpl который умеет и должен это делать

2023-09-09 09:02 UTC, wezzen approved these changes

2023-09-09 09:04 UTC, merged